#!/bin/bash
PATH=/usr/local/bin:$PATH
notifier=/usr/local/bin/terminal-notifier

# Give the network a chance to connect
sleep 10

brew update > /dev/null 2>&1
outdated=`brew outdated | sort | tr '\n' ' '`

if [ ! -z "$outdated" ]; then
    $notifier \
        -group com.beeler.brew-notifier \
        -title "Homebrew Updates Available" \
        -message "$outdated" \
        -activate com.apple.Terminal > /dev/null 2>&1
fi
